#!/bin/sh

initwireless_calibration() {
	mkdir -p /tmp/wlanconfig
	read_img wlanconfig /tmp/wlanconfig/wlanconfig_cal_files.tar.gz
	tar xzf /tmp/wlanconfig/wlanconfig_cal_files.tar.gz -C /tmp/wlanconfig/
	chown -R nwk:nwk /tmp/wlanconfig
	chmod 550 /tmp/wlanconfig
	chmod 440 /tmp/wlanconfig/*
}

boot_hook_add preinit_main initwireless_calibration
